//! Merkle tree matching the on-chain verifier.
//!
//! `CWEPayouts` verifies withdrawals against a committed root using
//! `MerkleProof.sol`, so this tree MUST reproduce its construction exactly:
//!
//! * **leaf**   = `keccak256(work_id ‖ amount_as_uint256_be)` — the same bytes
//!   `CWEPayouts.leafHash` hashes (`abi.encodePacked(bytes32, uint256)`).
//! * **parent** = `keccak256(concat(sorted(left, right)))` — pairs are ordered
//!   by hash value before hashing, so a proof needs no left/right flags.
//! * **odd node**: a level with an odd count carries its last node up unchanged.
//!
//! If any of these diverged from the Solidity side, `withdraw` would revert with
//! `BadProof`; the WP7 end-to-end demo exercises exactly that path on Anvil.

use cwe_wallet_zk::keccak256;

/// Compute the leaf hash for a `(work_id, amount)` credit, identical to
/// `CWEPayouts.leafHash`.
pub fn leaf_hash(work_id: [u8; 32], amount: u128) -> [u8; 32] {
    // 64-byte pre-image: 32-byte work id followed by the amount as a 32-byte
    // big-endian word (a u128 fits in the low 16 bytes; the high 16 stay zero).
    let mut buf = [0u8; 64];
    buf[0..32].copy_from_slice(&work_id);
    buf[48..64].copy_from_slice(&amount.to_be_bytes());
    keccak256(&buf)
}

/// Hash two nodes after ordering them, matching `MerkleProof._hashPair`.
fn hash_pair(a: [u8; 32], b: [u8; 32]) -> [u8; 32] {
    // Concatenate the smaller hash first so the parent is order-independent.
    let (lo, hi) = if a <= b { (a, b) } else { (b, a) };
    let mut buf = [0u8; 64];
    buf[0..32].copy_from_slice(&lo);
    buf[32..64].copy_from_slice(&hi);
    keccak256(&buf)
}

/// A Merkle tree over a fixed, ordered list of leaves, able to produce inclusion
/// proofs the on-chain verifier accepts.
pub struct MerkleTree {
    /// Every level, bottom (leaves) to top (root). `levels[0]` are the leaves and
    /// the final level holds the single root.
    levels: Vec<Vec<[u8; 32]>>,
}

impl MerkleTree {
    /// Build a tree from leaves (in the caller's chosen, stable order).
    ///
    /// The order matters: a leaf's proof is generated by its index, so the caller
    /// must remember which index each work maps to. Panics on an empty leaf set,
    /// which is a caller bug (an epoch with zero credited works should not build a tree).
    pub fn build(leaves: Vec<[u8; 32]>) -> Self {
        assert!(
            !leaves.is_empty(),
            "cannot build a Merkle tree with no leaves"
        );
        let mut levels = vec![leaves];
        // Fold pairs upward until a single root remains.
        while levels.last().unwrap().len() > 1 {
            let current = levels.last().unwrap();
            let mut next = Vec::with_capacity(current.len().div_ceil(2));
            let mut i = 0;
            while i < current.len() {
                if i + 1 < current.len() {
                    // A full pair: hash the two siblings together.
                    next.push(hash_pair(current[i], current[i + 1]));
                    i += 2;
                } else {
                    // A lone odd node: carry it up unchanged.
                    next.push(current[i]);
                    i += 1;
                }
            }
            levels.push(next);
        }
        MerkleTree { levels }
    }

    /// The committed root of the tree.
    pub fn root(&self) -> [u8; 32] {
        // The top level always holds exactly one node after `build`.
        self.levels.last().unwrap()[0]
    }

    /// The inclusion proof (sibling hashes, leaf→root) for the leaf at `index`.
    pub fn proof(&self, index: usize) -> Vec<[u8; 32]> {
        let mut proof = Vec::new();
        let mut idx = index;
        // Walk every level except the root, collecting the sibling at each step.
        for level in &self.levels[..self.levels.len() - 1] {
            // The sibling sits at the paired index (flip the lowest bit).
            let sibling = idx ^ 1;
            if sibling < level.len() {
                proof.push(level[sibling]);
            }
            // else: this node was the carried-up odd one — it has no sibling here.
            idx /= 2; // move to the parent's index in the next level
        }
        proof
    }
}

/// Recompute the root implied by `leaf` + `proof`, mirroring `MerkleProof.verify`.
/// Used by tests to confirm generated proofs are self-consistent.
pub fn verify(proof: &[[u8; 32]], root: [u8; 32], leaf: [u8; 32]) -> bool {
    let mut computed = leaf;
    for sibling in proof {
        computed = hash_pair(computed, *sibling);
    }
    computed == root
}

#[cfg(test)]
mod tests {
    use super::*;

    fn wid(fill: u8) -> [u8; 32] {
        [fill; 32]
    }

    /// Every leaf's generated proof must reconstruct the root, for tree sizes that
    /// exercise both even and odd (carried-node) levels.
    #[test]
    fn proofs_verify_for_various_sizes() {
        for n in 1usize..=8 {
            let leaves: Vec<[u8; 32]> = (0..n)
                .map(|i| leaf_hash(wid(i as u8), (i as u128 + 1) * 1000))
                .collect();
            let tree = MerkleTree::build(leaves.clone());
            let root = tree.root();
            for (i, leaf) in leaves.iter().enumerate() {
                assert!(verify(&tree.proof(i), root, *leaf), "size {n}, leaf {i}");
            }
        }
    }

    /// A single-leaf tree has the leaf as its root and an empty proof.
    #[test]
    fn single_leaf_tree() {
        let leaf = leaf_hash(wid(1), 5);
        let tree = MerkleTree::build(vec![leaf]);
        assert_eq!(tree.root(), leaf);
        assert!(tree.proof(0).is_empty());
    }

    /// leaf_hash is deterministic and distinguishes both the work id and amount.
    #[test]
    fn leaf_hash_distinguishes_inputs() {
        assert_eq!(leaf_hash(wid(1), 100), leaf_hash(wid(1), 100));
        assert_ne!(leaf_hash(wid(1), 100), leaf_hash(wid(2), 100));
        assert_ne!(leaf_hash(wid(1), 100), leaf_hash(wid(1), 101));
    }

    /// A tampered proof does not verify.
    #[test]
    fn tampered_proof_fails() {
        let leaves = vec![leaf_hash(wid(0), 10), leaf_hash(wid(1), 20)];
        let tree = MerkleTree::build(leaves.clone());
        let mut proof = tree.proof(0);
        proof[0][0] ^= 0xFF; // corrupt one byte
        assert!(!verify(&proof, tree.root(), leaves[0]));
    }
}
