//! WebAssembly core for the CWE browser extension (WP6).
//!
//! This crate is the Rust brain behind the JavaScript MV3 shell. It exposes three
//! capabilities, all reusing the workspace's tested libraries so the extension,
//! the settlement job, and the simulator share one implementation:
//!
//! * [`fingerprint`] — recognise a work from its audio samples (WP3 stub).
//! * [`commitment`] — build the usage commitment a user submits on-chain (WP4).
//! * [`WasmSession`] — accrue listening time per work, epoch-aware (WP4).
//!
//! Everything here is a thin `wasm_bindgen` wrapper; the logic lives in the
//! `cwe-fingerprint` and `cwe-wallet-zk` crates.

#![forbid(unsafe_code)]

use std::str::FromStr;

use cwe_fingerprint::Fingerprint;
use cwe_wallet_zk::commit::Opening;
use cwe_wallet_zk::session::SessionStore;
use cwe_wallet_zk::Bytes32;
use wasm_bindgen::prelude::*;

/// Compute the fingerprint of a buffer of audio sample bytes.
///
/// Returns the canonical `fp:<64 hex>` identifier. In Phase 1 this is the
/// deterministic SHA-256 stub (WP3); the API is stable across the swap to a real
/// perceptual fingerprint later.
#[wasm_bindgen]
pub fn fingerprint(samples: &[u8]) -> String {
    Fingerprint::compute(samples).to_string()
}

/// Build the usage commitment for a work.
///
/// Given the work's on-chain id, minutes listened, and a random 32-byte salt (all
/// hex), returns the `0x`-hex keccak256 commitment the user submits on-chain. The
/// salt must be generated by the caller (the shell uses the browser's CSPRNG).
// `minutes` is `u32` (not `u64`) because wasm-bindgen maps `u64` to a JS `BigInt`,
// which is awkward for callers; a `u32` maps to a plain `Number` and is ample for
// per-epoch minutes. It is widened to `u64` internally to match the shared type.
#[wasm_bindgen]
pub fn commitment(work_id_hex: &str, minutes: u32, salt_hex: &str) -> Result<String, JsError> {
    // Parse the hex inputs into 32-byte values, surfacing a clear JS error on bad input.
    let work = Bytes32::from_str(work_id_hex).map_err(to_js)?;
    let salt = Bytes32::from_str(salt_hex).map_err(to_js)?;
    // Compute the commitment and render it as 0x-hex.
    Ok(Opening::new(work, minutes as u64, salt).commit().0.to_string())
}

/// A session store exposed to JavaScript.
///
/// The shell persists the store across service-worker restarts by saving
/// [`WasmSession::snapshot`] to `chrome.storage` and rebuilding with
/// [`WasmSession::restore`].
#[wasm_bindgen]
pub struct WasmSession {
    /// The wrapped Rust store holding all accrual state.
    inner: SessionStore,
}

#[wasm_bindgen]
impl WasmSession {
    /// Create a fresh store anchored to the epoch containing `now_secs`.
    ///
    /// `now_secs` is `f64` (JS `Number`, e.g. `Date.now() / 1000`) rather than
    /// `u64` to avoid forcing callers through `BigInt`; it is truncated to whole
    /// seconds internally.
    #[wasm_bindgen(constructor)]
    pub fn new(now_secs: f64) -> WasmSession {
        WasmSession { inner: SessionStore::new(now_secs as u64) }
    }

    /// Rebuild a store from a JSON snapshot previously returned by [`snapshot`].
    ///
    /// [`snapshot`]: WasmSession::snapshot
    pub fn restore(json: &str) -> Result<WasmSession, JsError> {
        // Deserialise the persisted state, mapping a parse failure to a JS error.
        let state = serde_json::from_str(json).map_err(to_js)?;
        Ok(WasmSession { inner: SessionStore::from_state(state) })
    }

    /// Serialise the store's state to JSON for persistence.
    pub fn snapshot(&self) -> String {
        // The state is always serialisable, so this cannot fail in practice.
        serde_json::to_string(self.inner.snapshot()).unwrap_or_else(|_| "{}".to_string())
    }

    /// The epoch this store is accruing into.
    pub fn epoch(&self) -> u64 {
        self.inner.epoch()
    }

    /// Open a playback session accruing to a work (hex id).
    pub fn start(&mut self, session_id: String, work_id_hex: String) -> Result<(), JsError> {
        let work = Bytes32::from_str(&work_id_hex).map_err(to_js)?;
        self.inner.start(session_id, work);
        Ok(())
    }

    /// Add elapsed seconds to an open session; returns false if unknown.
    /// `dt_secs` is `u32` (JS `Number`) — one progress tick is never that large.
    pub fn add_time(&mut self, session_id: String, dt_secs: u32) -> bool {
        self.inner.add_time(&session_id, dt_secs as u64)
    }

    /// Close a session; returns false if it was not open.
    pub fn stop(&mut self, session_id: String) -> bool {
        self.inner.stop(&session_id)
    }

    /// Drain the epoch's accrued time to a JSON array of `{work_id, minutes}`.
    pub fn flush(&mut self) -> String {
        let usage = self.inner.flush();
        // Serialise the usage entries; an empty array on the (unreachable) error path.
        serde_json::to_string(&usage).unwrap_or_else(|_| "[]".to_string())
    }
}

/// Convert any `Display` error into a JS-side `JsError`.
fn to_js<E: std::fmt::Display>(e: E) -> JsError {
    JsError::new(&e.to_string())
}
