.PHONY: devnet deploy stop

devnet:
	@echo "Starting local devnet (Hardhat) + services stubs"
	# TODO: docker compose up -d

deploy:
	@echo "Deploying contracts"
	# TODO: hardhat deploy

stop:
	docker compose -f ops/docker-compose.dev.yml down || true
